title: ChessBuddy Homepage
description: ChessBuddy tries to be your chess buddy and improve your chess.
theme: just-the-docs

url: https://aniusw.github.io/chessbuddy

aux_links:
  Template Repository: https://github.com/aniusw/chessbuddy
