title: ChessBuddy
description: ChessBuddy - Your Ultimate Chess Companion
theme: just-the-docs

url: https://aniusw.github.io/chessbuddy

aux_links:
  Site Repository: https://github.com/aniusw/chessbuddy

# logo: "/chessbuddy.png"